permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "GANethe"
first_name: "GANethe's"
last_name: "Angiosperm Study Notes"
blog_title: "GANs"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "pasinduland"
copyright_year: "2020"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: "ganlu1994"
facebook: "mepasindu"
linkined_url: ""
